<div class="hide"></div>
<div class="about_wrapper">
 <img src="images/animalfarm_header.jpg" class="1/1"/>
</div>
<div class="about_content pt+">
  <h3 class="ml+ palm-pl palm-m0"><span>ABOUT</span></h1>
  <div class="o-layout o-layout--flush clear p+ palm-p">
    <div class="o-layout__item one-third palm-one-whole left z1">
      Abseits des städtischen Lärms, den dunklen Clubs und der Anonymität der Mega-Festivals laden wir unsere Freunde und deren Freunde ein zweites Mal auf unseren geliebten Bauernhof ein. Gemütlich und intim werden 700 Freunde das Wochenende lang tanzen und die frische Luft genießen.
    </div>
    <div class="o-layout__item one-third palm-one-whole left">
      <div class="logo-header pt+">
        &nbsp;
        <!--<img class="1/1" src="images/schwein.png"/>-->
      </div>
    </div>
    <div class="o-layout__item one-third palm-one-whole left">
      Unsere wunderbare kleine Farm liegt ein Stündchen Fahrzeit südlich von Berlin in der Nähe von Cottbus mitten im Herzen. In der Nähe eines Sees werden auf zwei Dancefloors und einem Chill-Out Bereich über 60 DJs und Live Acts zu kühlen Drinks und lecker Essen Euch die Zeit vertreiben.
    </div>
    <div class="o-layout__item one-whole">
      <div class="center pt clear">
        <!-- <h2>30.06. - 02.07.2017</h2><br><br> -->
        <span class="font__amatic alpha">Jedem Tierchen sein Pläsierchen</span><br>
        <!-- <br>
        <span class="alpha">Animal<span><br>
        <span class="alpha">Farm</span><br> -->
      </div>
    </div>
  </div>
</div>
