<div class="clear">&nbsp;</div>
<h1 class="ml+ palm-pl palm-m0">ABOUT</h1>
<div class="layout layout--flush clear p+ palm-p">
  <div class="layout__item one-third palm-one-whole left z1">
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
  </div>
  <div class="layout__item one-third palm-one-whole left">
    &nbsp;
    <div class="logo-header relative pt+">
      <img class="1/1" src="images/schwein.png"/>
    </div>
  </div>
  <div class="layout__item one-third palm-one-whole left">
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
  </div>
  <div class="layout__item one-whole">
    <div class="center pt clear">
      <h2>30.06. - 02.07.2017</h2><br><br>
      <span class="font__amatic alpha">Jedem Tierchen sein Pläsierchen</span><br>
      <br>
      Animal<br>
      Farm<br>
    </div>
  </div>
</div>
