<div class="border mh+ palm-m text--center">
  <h3><span>LIMITED SECOND MOUSE TICKETS</span></h3>
  <div class="palm-p0 palm-m0 pt+ tiles 1/2">
    Tickets werden in drei Phasen verkauft und sind limitiert, da wir die Animal Farm klein und gemütlich halten wollen.
    <ul>
      <li style="text-decoration: line-through;">Early Birds (Ausverkauft)  – 50€ zzgl. 5€ Müllpfand</li>
      <li><a class="font__lato" target="_blank" href="https://www.eventbrite.de/e/animal-farm-festival-2017-tickets-32212955818">Second Mouse – 60€ zzgl. 5€ Müllpfand</a></li>
      <li>Late Sloth – 70€ zzgl. 5€ Müllpfand</li>
    </ul>
  </div>
  <div class="palm-p0 palm-m0 pt+ tiles 1/2">
    Tickets kann man auch hier kaufen:
    <ul>
      <li><a class="font__lato" target="_blank" href="http://www.schwelgerei.berlin/">Schwelgerei, Kreuzberg, Sanderstr. 2</a></li>
      <li><a class="font__lato" target="_blank" href="http://tantefrizzante.de/konzept/">Tante Frizzante, Neukölln, Hermannstr. 95</a></li>
    </ul>
  </div>
</div>
