<div class="center">
  <h1><a class="font__lato" target="_blank" href="https://www.eventbrite.de/e/animal-farm-festival-2017-tickets-32212955818">LIMITED SECOND MOUSE TICKETS</a></h1>
</div>
<br><br><br>
<div class="ml+ palm-p0 palm-m0">
  Tickets werden in drei Phasen verkauft und sind limitiert, da wir die Animal Farm klein und gemütlich halten wollen.
  <ul>
    <li style="text-decoration: line-through;">Early Birds (Ausverkauft)  – 50€ zzgl. 5€ Müllpfand</li>
    <li><a class="font__lato" target="_blank" href="https://www.eventbrite.de/e/animal-farm-festival-2017-tickets-32212955818">Second Mouse – 60€ zzgl. 5€ Müllpfand</a></li>
    <li>Late Sloth – 70€ zzgl. 5€ Müllpfand</li>
  </ul>
</div>
<div class="ml+ palm-p0 palm-m0">
  Tickets kann man auch hier kaufen:
  <ul>
    <li>Schwelgerei, Kreuzberg, Sanderstr. 2</li>
    <li>Tante Frizzante, Neukölln, Hermannstr. 95</li>
  </ul>
</div>
