<?
  $colorNumbers = [1,2,3,4,5,6];
  function array_pop_at_position(&$arr = [], $pos)
  {
    if (count($arr)-1 >= $pos) {
      $value = $arr[$pos];
      array_splice($arr, $pos, 1);
      return $value;
    }
  }
?>
<h3 class="ml+ clear palm-p0 palm-m0 blue__dark">Infos</h3>
<div class="mv+">
  <div class="tiles o-pack o-pack--small desk-two-thirds lap-two-thirds palm-one-whole">
    <div class="o-pack__item desk-one-third lap-one-third palm-one-half colors-<?=array_pop_at_position($colorNumbers, rand(0,count($colorNumbers)-1))?>">
      <h4>Camping</h4>
      <div>
        Ab Freitag mittag könnt Ihr auf das Gelände.
        Bitte benutzt die ausgewiesenen Flächen zum Zelten. Bitte nicht im Wald zelten! Aufgestellte Zelte werden von uns sofort abgebaut.
      </div>
    </div><!--
    --><div class="o-pack__item desk-one-third lap-one-third palm-one-half colors-<?=array_pop_at_position($colorNumbers, rand(0,count($colorNumbers)-1))?>">
      <h4>Feuer &amp; Grillen</h4>
      <div>
        Aufgrund starker Waltbrandgefahr sind offene Feuer strengstens untersagt!
      </div>
    </div><!--
    --><div class="o-pack__item desk-one-third lap-one-third palm-one-half colors-<?=array_pop_at_position($colorNumbers, rand(0,count($colorNumbers)-1))?>">
      <h4>Tickets und Abendkasse</h4>
      <div>
        Es wird keine Abendkasse auf dem Festival geben. Tickets sind limitiert und werden in drei Phasen verkauft.
      </div>
    </div>
  </div>
  <div class="tiles o-pack o-pack--small desk-two-thirds lap-two-thirds palm-one-whole">
    <div class="o-pack__item desk-one-third lap-one-third palm-one-half colors-<?=array_pop_at_position($colorNumbers, rand(0,count($colorNumbers)-1))?>">
      <h4>Bändchenkontrolle</h4>
      <div>
        Es wird auf dem Festivalgelände Bändchenkontrollen geben. Passt auf Eure Bändchen auf.
      </div>
    </div><!--
    --><div class="o-pack__item desk-one-third lap-one-third palm-one-half colors-<?=array_pop_at_position($colorNumbers, rand(0,count($colorNumbers)-1))?>">
      <h4>Kein Konfetti!</h4>
      <div>
        Lasst das Konfetti zuhause. Das Zeug bekommt man vom Boden einfach nicht mehr weg.
      </div>
    </div><!--
    --><div class="o-pack__item desk-one-third lap-one-third palm-one-half colors-<?=array_pop_at_position($colorNumbers, rand(0,count($colorNumbers)-1))?>">
      <h4>Haftung</h4>
      <div>
        Die Teilnahme an dem Animal Farm Festival erfolgt grundsätzlich auf eigene Verantwortung.
Wir übernehmen keine Haftung für körperliche und sachliche Schäden während der Veranstaltung und auch nicht im Rahmen der An- und Abreise.
      </div>
    </div>
  </div>
</div>
