<h3 class="ml+ mv0 clear palm-p0 palm-m0 blue__dark"><span>Infos</span></h3>
<div class="mv+">
  <div class="tiles o-pack o-pack--small desk-two-thirds lap-two-thirds palm-one-whole">
    <div class="border text--center o-pack__item desk-one-third lap-one-third palm-one-whole bg--turquoise">
      <h4><span class="pv0">Camping</span></h4>
      <div class="pt">
        &mdash;<br>
        Ab Freitag mittag könnt Ihr auf das Gelände.
        Bitte benutzt die ausgewiesenen Flächen zum Zelten. Bitte nicht im Wald zelten! Aufgestellte Zelte werden von uns sofort abgebaut.<br>
        &mdash;
      </div>
    </div><!--
    --><div class="border text--center o-pack__item desk-one-third lap-one-third palm-one-whole bg--turquoise">
      <h4 ><span class="pv0">Feuer &amp; Grillen</span></h4>
      <div class="pt">
        &mdash;<br>
        Aufgrund starker Waltbrandgefahr sind offene Feuer strengstens untersagt!<br>
        &mdash;
      </div>
    </div><!--
    --><div class="border text--center o-pack__item desk-one-third lap-one-third palm-one-whole bg--turquoise">
      <h4 ><span class="pv0">Abendkasse</span></h4>
      <div class="pt">
        &mdash;<br>
        Es wird keine Abendkasse auf dem Festival geben. Tickets sind limitiert und werden in drei Phasen verkauft.<br>
        &mdash;
      </div>
    </div>
  </div>
  <div class="tiles o-pack o-pack--small desk-two-thirds lap-two-thirds palm-one-whole">
    <div class="border text--center o-pack__item desk-one-third lap-one-third palm-one-whole bg--turquoise">
      <h4 ><span class="pv0">Bändchen</span></h4>
      <div class="pt">
        &mdash;<br>
        Es wird auf dem Festivalgelände Bändchenkontrollen geben. Passt auf Eure Bändchen auf.<br>
        &mdash;
      </div>
    </div><!--
    --><div class="border text--center o-pack__item desk-one-third lap-one-third palm-one-whole bg--turquoise">
      <h4 ><span class="pv0">Kein Konfetti!</span></h4>
      <div class="pt">
        &mdash;<br>
        Lasst das Konfetti zuhause. Das Zeug bekommt man vom Boden einfach nicht mehr weg.<br>
        &mdash;
      </div>
    </div><!--
    --><div class="border text--center o-pack__item desk-one-third lap-one-third palm-one-whole bg--turquoise">
      <h4 ><span class="pv0">Haftung</span></h4>
      <div class="pt">
        &mdash;<br>
        Die Teilnahme an dem Animal Farm Festival erfolgt grundsätzlich auf eigene Verantwortung.
Wir übernehmen keine Haftung für körperliche und sachliche Schäden während der Veranstaltung und auch nicht im Rahmen der An- und Abreise.<br>
&mdash;
      </div>
    </div>
  </div>
</div>
