<div class="sc-link absolute">
  <a href="http://soundcloud.com/animalfarmfestival">
    <img src="https://w.soundcloud.com/icon/assets/images/orange_white_64-94fc761.png" class="one-whole">
  </a>
</div>
<h3 class="ml+ blue__dark">GET IN THE MOOD</h3>
<div class="sc-wrapper center mv+">
  <iframe width="650" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/197791996&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
</div>
