<?
  $name = 'artists';
  spl_autoload_register(function ($name) {
    echo "Want to load $name.\n";
    throw new Exception("Unable to load $name.");
  });

  include_once( dirname( __DIR__ ) . '/../repositories/artists.php' );
  $artists = new Artists();
?>
<div class="layout__item one-sixth left pt+ palm-hide">
  <div class="vertical right bold">AMBIENT FLOOR</div>
</div>
<div class="layout__item one-sixth left palm-one-whole desk-hide lap-hide">
  <h3 class="ml+ clear palm-p0 palm-m0 left pt"><span>LINEUP</span></h3>
</div>
<div class="layout__item four-sixths left palm-one-whole">
    <?
      foreach ($artists->getAll() as $name) {
        echo "<div class='layout__item 1/5 left font__amatic delta'>".$name."</div>";
      }
    ?>
</div>
<div class="layout__item one-sixth left palm-hide">
  <h3 class="ml+ clear palm-pl palm-m0 left pt"><span>LINEUP</span></h3>
</div>
<div class="layout__item one-sixth left pt+ palm-one-whole desk-hide lap-hide">
  <div class="vertical right bold">AMBIENT FLOOR</div>
</div>

<div class="clear">&nbsp;</div>
