<?
  $name = 'artists';
  spl_autoload_register(function ($name) {
    echo "Want to load $name.\n";
    throw new Exception("Unable to load $name.");
  });

  include_once( dirname( __DIR__ ) . '/../repositories/artists.php' );
  $artists = new Artists();
?>
<div class="o-pack o-pack--auto o-pack--middle">
  <div class="palm-pl0 text--center">
    <h3 class="stars m0 pv clear palm-p0 palm-m0 text--left"><span>LINEUP</span></h3>
  </div>
  <div class="o-layout--flush">
      <?
        $i = 0;
        foreach ($artists->getAll() as $artist) {
          if (count($artist['link'])){
            $name = '<div>'.$artist['name'].'</div>';
            $link = '<a target="_blank" class="no-deco ml" href="'.$artist['link'].'">'.$artist['link'].'</a>';
          }
          echo "<div class='pv- font__amatic delta o-layout__item 1/2'>".$name.$link."</div>";
        }
      ?>

  </div>


</div>
