<?
  $name = 'artists';
  spl_autoload_register(function ($name) {
    echo "Want to load $name.\n";
    throw new Exception("Unable to load $name.");
  });

  include_once( dirname( __DIR__ ) . '/../repositories/artists.php' );
  $artists = new Artists();
?>
<div class="o-pack o-pack--auto o-pack--middle">
  <div class="o-pack__item palm-one-whole pl+ palm-pl-">
    <h3 class="m0 clear palm-p0 palm-m0 left palm-one-whole"><span>LINEUP</span></h3>
  </div><!--
  --><div class="o-pack__item palm-hide">
      <table>
        <tr>
        <?
          $i = 0;
          foreach ($artists->getAll() as $artist) {
            $i++;
            $name = $artist['name'];
            if (count($artist['link'])){
              $name = '<a target="_blank" class="no-deco" href="'.$artist['link'].'">'.$name.'</a>';
            }
            echo "<td class='pv- font__amatic delta ph'>".$name."</td>";

            if ($i % 5 == 0) {
              echo '</tr><tr>';
            }

          }
        ?>
        </tr>
      </table>
  </div><!--
  --><div class="o-pack__item palm-one-whole hide palm-show o-layout ph">
  <?
    foreach ($artists->getAll() as $artist) {
      $name = $artist['name'];
      if (count($artist['link'])){
        $name = '<a target="_blank" class="no-deco" href="'.$artist['link'].'">'.$name.'</a>';
      }
      echo "<div class='pv- font__amatic text--center delta ph o-layout__item 1/2'>".$name."</div>";
    }
  ?>
  </div><!--
  --><div class="o-pack__item palm-one-whole palm-pl-">
    <div class="vertical bold mr gamma">MORE TBA.</div>
  </div>
</div>
