
  <h3 class="stars pv mv0"><span>NEWSLETTER</span></h3>
  <div class="center">

      <!-- Begin MailChimp Signup Form -->
      <style type="text/css">
      	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
      	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
      	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
      </style>
      <div id="mc_embed_signup">
      <form action="//facebook.us13.list-manage.com/subscribe/post?u=527388922900503ff9090ed27&amp;id=872fc2a7a2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div class="o-layout o-layout--flush">
          <div class="o-layout__item mc-field-group p 1/3 palm-1/1">
             <input placeholder="NAME *" type="text" value="" name="FNAME" class="" id="mce-FNAME">
           </div><!--
            --><div id="mc_embed_signup_scroll" class="o-layout__item p 1/3 palm-1/1">
            	<input placeholder="E-MAIL *" type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
            </div><!--
             --><div class="o-layout__item mc-field-group p 1/3 palm-1/1">
            	<input type="text" placeholder="TEL" value="" name="MMERGE3" class="" id="mce-MMERGE3">
            </div>
         </div>
        	<div id="mce-responses" class="clear">
        		<div class="response" id="mce-error-response" style="display:none"></div>
        		<div class="response" id="mce-success-response" style="display:none"></div>
        	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_527388922900503ff9090ed27_872fc2a7a2" tabindex="-1" value=""></div>
          <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
          </div>

      </form>
      </div>
      <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text'; /*
       * Translated default messages for the $ validation plugin.
       * Locale: DE
       */
      $.extend($.validator.messages, {
      	required: "Dieses Feld ist ein Pflichtfeld.",
      	maxlength: $.validator.format("Geben Sie bitte maximal {0} Zeichen ein."),
      	minlength: $.validator.format("Geben Sie bitte mindestens {0} Zeichen ein."),
      	rangelength: $.validator.format("Geben Sie bitte mindestens {0} und maximal {1} Zeichen ein."),
      	email: "Geben Sie bitte eine gültige E-Mail Adresse ein.",
      	url: "Geben Sie bitte eine gültige URL ein.",
      	date: "Bitte geben Sie ein gültiges Datum ein.",
      	number: "Geben Sie bitte eine Nummer ein.",
      	digits: "Geben Sie bitte nur Ziffern ein.",
      	equalTo: "Bitte denselben Wert wiederholen.",
      	range: $.validator.format("Geben Sie bitten einen Wert zwischen {0} und {1}."),
      	max: $.validator.format("Geben Sie bitte einen Wert kleiner oder gleich {0} ein."),
      	min: $.validator.format("Geben Sie bitte einen Wert größer oder gleich {0} ein."),
      	creditcard: "Geben Sie bitte ein gültige Kreditkarten-Nummer ein."
      });}(jQuery));var $mcj = jQuery.noConflict(true);</script>
      <!--End mc_embed_signup-->

  </div>
