<div class="palm-m0">
  <h3 class="clear palm-p0 palm-m0 mt0 stars"><span>Anfahrt</span></h3>
  <div class="pv+ palm-m0 text--center">
    So kommt ihr auf die Animal Farm:<br>
    <br>
    Shuttleservice<br><br>
    Ab Berlin<br>
    Es gibt einen Shuttleservice mit Tickets in begrenzter Anzahl, die Ihr hier bestellen könnt.<br>
    <a class="font__lato" href="http://buff.ly/2n2ZdQ4" target="_blank">http://buff.ly/2n2ZdQ4</a><br>
    <br>
    &mdash;<br>
    Ab Köln<br>
    Es gibt einen Shuttleservice mit Tickets in begrenzter Anzahl. Infos gibt es hier:<br>
    <a class="font__lato" href="http://bit.ly/2swS93d" target="_blank">http://bit.ly/2swS93d</a><br>
    <br>
    &mdash;<br>
    Mit den Öffentlichen:<br>
    Fahrt mit den Regionalzug nach Altdöbern. Fahrt zusammen und holt Euch Gruppentickets.<br>
    Ab Altdöbern könnt ihr mit dem Fahrad fahren (30min bzw. 9km) oder gegen einen kleinen<br>
    Unkostenbeitrag einen Shuttleservice von uns nehmen, solange die Züge fahren.<br>
  </div>
</div>
