<div class="border palm-m0 text--center">
  <h3 class="blue_baby"><span>PROGRAMM</span></h3>
  <div class="palm-m0 pt+ tiles">
    Was wäre die Animal Farm ohne sinnstiftende und lehrreiche Workshops?<br>
    Dieses Jahr werden diese Workshops angeboten:
    <ul>
      <li>
        <h5><a class="font__lato" data-fancybox="modal" data-src="#lovesalon" href="javascript:;">Love Salon</a></h5>
      </li>
      <li>
        <h5><a class="font__lato" data-fancybox="modal" data-src="#kakao" href="javascript:;">Kakao Zeremonie mit Contact Dance</a></h5>
      </li>
      <li>
        <h5><a class="font__lato" data-fancybox="modal" data-src="#dharma" href="javascript:;">Dharma Yoga Workshop</a></h5>
      </li>
      <li>
        <h5><a class="font__lato" data-fancybox="modal" data-src="#thai" href="javascript:;">Thai-Yoga-Massage</a></h5>
      </li>
      <li>
        <h5><a class="font__lato" data-fancybox="modal" data-src="#mut" href="javascript:;">Mut zur Freiheit</a></h5>
      </li>
    </ul>
  </div>
</div>
<p id="lovesalon" class="hide lightbox-wrapper">
Love Salon<br><br>
Ein totaler Raum - der Liebe gewidmet,<br>
In all ihren Spiel-Arten und Facetten.<br>
Wir wollen gemeinsam das Phänomen ihrer An- und Abwesenheit ergründen.<br>
Mit Musik umrahmt - den Live Love Songs,<br>
Von purem Klang getragen – als Meditation & Ritual,<br>
Inspirativer Austausch – durch Sprache, Poesie & Gespräch,<br>
Angeregte Bewegung & Berührung – durch Interaktion.<br>
Eine Einladung<br>
zum Lauschen & Schauen,<br>
Empfinden & Entdecken.<br>
Für die radikale Partizipation<br>
IN LIEBE<br>
<br>
Saskia Baumgart & Maria Schubart
</p>
<p id="kakao" class="hide lightbox-wrapper">
  Kakao Zeremonie mit Contact Dancey<br><br>
  Kakao-Zeremonien- und Rituale werden immer beliebter. Ein Mythos besagt, dass die Heilpflanze immer dann ins Bewusstsein der Menschen zurück kommt, wenn ein Wandel ansteht oder Mutter Erde Unterstützung benötigt. Kein Wunder also, dass "Mama Kakao" wieder zurück gekehrt ist um mit ihrer Weisheit und sanften Art die Menschen dabei zu unterstützen ihr Herz zu öffnen, sich selbst und ihre Mitmenschen besser fühlen und verstehen zu können und das Wunder des Lebens und Seins und die Verbundenheit mit der Natur wieder zu spüren.<br>
<br>
Kakao wirkt zwar nicht psychedelisch eignet sich aber dennoch (oder vielleicht gerade deswegen) sehr gut um schamanisch "zu reisen".<br>
<br>
Auf eine solche Reise wollen wir DICH hier einladen 🙂<br>
<br>
Gemeinsam eröffnen wir die Reise mit einer geführten Meditation um unser Herz zu öffnen und uns mit dem Geist der Pflanze zu verbinden.<br>
<br>
Anschließend bekommt jeder seinen magischen Trank. Bevor wir gemeinsam trinken, kann jeder seine guten Gedanken und Wünsche für Heilung in den Kakao hineingeben. Dann tönen wir gemeinsam und anschließend nehmen wir die köstliche Medizin ein.<br>
<br>
Der zweite Teil der Reise wird mit Musik begleitet und hilft dir zunächst ganz bei Dir anzukommen um dann Schritt für Schritt den Raum zu öffnen und eventuell auch mit deinen Mitmenschen in Kontakt und Verbindung zu kommen.<br>
<br>
DU wirst vor allem spüren wie liebevoll und sanft Kakao mit dir arbeitet und getragen sein von einer Welle aus Leichtigkeit, Liebe und Glückseeligkeit.<br>
<br>
Die Zeremonie inklusive der musikalischen Begleitung wird von Steffen Kirchhoff durchgeführt. Steffen hat zunächst zahlreiche Kakao-Zeremonien mit Schamanen begleitet und war dort als Assitent tätig bevor er dieses Jahr im Sommer damit begann eigene Zeremonien und Rituale durchzuführen.<br>
<br>
Wir arbeiten mit 100% rohem Kakao von exklusiver Qualität , welcher aus einer biologischen Farm aus Bali stammt und verwenden nur feinste Zutaten nach einem Original-Maya-Rezept
</p>

<p id="dharma" class="hide lightbox-wrapper">
  Dharma Yoga Workshop<br><br>
  “All is within.” Dharma Mittra<br><br>
  Wir – Nico, April, Mona, Hélène und Patricia – sind Teil des Teams im Dharma Yoga Studio Berlin, das vor über einem Jahr seine Türen in Berlin Neukölln geöffnet hat. Wir haben uns vorgenommen, Euch das Yoga-Universum ein wenig näher zu bringen, genauer Dharma Yoga, einen von unzähligen Stilen in Hatha Vinyasa, der seit fast 50 Jahren von Sri Dharma Mittra in New York gelehrt wird.<br>
In unseren Klassen flowt ihr nach einer kurzen Meditation aus der Kobra in den herabschauenden Hund und verwandelt euch später vielleicht von einer Schildkröte in eine Taube oder ein Kamel – im Yoga sind die meisten Körperhaltungen nämlich nach Tieren benannt und wir basteln bereits Animal-Flows.<br>
Neben dieser klassischen Yoga-Art bringen wir Euch weitere Yogastile und –techniken, sowie Workshops mit zum Festival. Weitere Informationen findet ihr demnächst im Programm und wer jetzt schon Lust bekommen hat, vorab mal bei uns vorbei zu schauen, findet uns hier: <a class="font__lato" style="color:inherit;" href="https://www.dharmayogaberlin.com" target="_blank">Dharma Yoga Berlin</a><br>
Bring your mat and see you there, und bis dahin<br>
<br>
„Be receptive!“
</p>
<p id="thai" class="hide lightbox-wrapper">
  So ein Festival ist natürlich immer `ne harte Nummer für den Körper. Damit Ihr mal zur<br>
  Abwechslung nicht total zerstört nach Hause kommt, wird Euch Mara vom Bittersweetyoga Thai-Yoga-Massagen anbieten.<br>
  Solch eine Massage besteht aus passiven, dem Yoga entnommenen Streckpositionen und Dehnbewegungen, Gelenkpositionen und Druckpunktmassagen. Danach seid ihr entspannter als eine Made im Speck<br>
  <br>
  <a class="font__lato" style="color:inherit;" href="http://www.bittersweetyoga.de/">http://www.bittersweetyoga.de/</a>
</p>
<p id="mut" class="hide lightbox-wrapper">
  Mut zur Freiheit<br><br>
Freiheit ist das, was uns alltäglich umgibt und doch nur in uns selbst existiert. Demokratische Freiheit ist das, was uns gleichzeitig befähigt, ein selbstbestimmtes Leben zu führen, und einschränkt, um im Konsens mit unseren Mitmenschen zu kooperieren. Sie ist vermeintlich das, was manchen Menschen fehlt. Wir nehmen uns Freiheiten; fordern sie ein; gewähren sie. Freiheit ist ein Entwurf; Eine menschliche Kategorie.<br>
<br>
In einem philosophischem Impuls-Vortrag möchte Tomasz Lachmann darüber sprechen, wie sich unsere Vorstellung von freiheitlichem Leben entwickelt hat, welche Schlüsse wir daraus ziehen können und warum es uns mutiges Handeln abverlangt, frei zu leben.<br>
<br>
about Tomasz.<br>
Tomasz Lachmann ist Kreativ-Unternehmer, Kommunikationsdesigner und Alltagsphilosoph. Er schreibt sachliche und prosaische Texte. Im Spannungsgefüge von gesellschaftlicher Transformation, aktiver Zukunftsgestaltung und aufklärender Öffentlichkeitsarbeit fühlt er sich zu Hause.
</p>
