<div class="border mh+ palm-m text--center">
  <h3 class="">PROGRAMM</h3>
  <div class="ml+ palm-p0 palm-m0 text--left"><br>Was wäre die Animal Farm ohne sinnstiftende und lehrreiche Workshops?<br>
    Dieses Jahr werden diese Workshops angeboten:
    <ul>
      <li>School of Love
        <ul>
          <li>TBD.</li>
        </ul>
      </li>
      <li>Tier-Yoga
        <ul>
          <li>TBD.</li>
        </ul>
      </li>
    </ul>
  </div>
</div>
