<div class="border mh+ palm-m text--center">
  <h3 class="yellow-to-blue"><span>PROGRAMM</span></h3>
  <div class="palm-m0 pt+ tiles 1/2 palm-one-whole">
    Was wäre die Animal Farm ohne sinnstiftende und lehrreiche Workshops?<br>
    Dieses Jahr werden diese Workshops angeboten:
    <ul>
      <li>School of Love (TBD.)</li>
      <li>Tier-Yoga (TBD.)</li>
      <li>Love Salon (TBD.)</li>
      <li>Kakao Zeremonie mit Contact Dance (TBD.)</li>
      <li>Bondage Workshop für Beginner (TBD.)</li>
    </ul>
  </div>
</div>
