<script src="<?=$_SERVER['REQUEST_URI']?>js/jquery-1.10.2.min.js"></script>
<script src="<?=$_SERVER['REQUEST_URI']?>js/jquery.animatescroll.min.js"></script>
<script src="<?=$_SERVER['REQUEST_URI']?>js/jquery.stickUp.min.js"></script>
<script>
  $(document).ready(function() {
    $('.navigation').stickUp({
      parts: ['about','news','ads','lineup','infos','programm', 'newsletter'],
      itemClass: 'navigation__item',
      itemHover: 'active',
    });
    if ($(window.location.hash+'').length) {
      //take id with name from hash param and scroll there
      $(window.location.hash+'').animatescroll();
    }

    $('.navigation a.navigation__item').each(function(i, el){
      $(el).click(function(){
        event.preventDefault();
        $('#'+$(el).data('target')+'').animatescroll();
      });
    })

    if ($(document).scrollTop() <= 1) {
      $('.navigation').removeClass('isStuck');
    }

    $(document).on('scroll', function() {
      if ($(document).scrollTop() <= 1) {
        $('.navigation').removeClass('isStuck');
      }
    });

  });
</script>
</body>
</html>
