<!DOCTYPE html>
<html>
  <head>
    <script src="<?=$_SERVER['REQUEST_URI']?>js/jquery-1.10.2.min.js"></script>
    <script src="<?=$_SERVER['REQUEST_URI']?>js/jquery.animatescroll.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?=$_SERVER['REQUEST_URI']?>css/main.css" /><link>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Lato:400,900" rel="stylesheet">
    <title>Animal Farm</title>
    <link rel="shortcut icon" href="<?=$_SERVER['REQUEST_URI']?>images/pig.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-91305187-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <body>
