<!DOCTYPE html>
<html>
  <head>
    <script src="<?=$_SERVER['REQUEST_URI']?>js/jquery-1.10.2.min.js"></script>
    <script src="<?=$_SERVER['REQUEST_URI']?>js/jquery.animatescroll.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?=$_SERVER['REQUEST_URI']?>css/main.css" /><link>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Lato:400,900" rel="stylesheet">
    <title>Animalfarm</title>
    <link rel="shortcut icon" href="<?=$_SERVER['REQUEST_URI']?>images/pig.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <body>
