<?
  $naviLeft = ["about" => "About", "lineup" => "Lineup", "news" => "News"];
  $naviRight = ["infos" => "Infos", ];#"programm" => "Programm", "tickets" => "Tickets", "contact" => "Kontakt"];
?>

<div class="left">
  <?foreach ($naviLeft as $key => $value) {?>
    <a class='mr gamma' data-target='<?=$key?>' href='#<?=$key?>'><?=$value?></a>
  <?}?>
</div>
<div class="right">
  <?foreach ($naviRight as $key => $value) {?>
    <a class='ml gamma' data-target='<?=$key?>' href='#<?=$key?>'><?=$value?></a>
  <?}?>
</div>
