<?
  $naviLeft = ["about" => "About", "news" => "News", "ads" => "Tickets", "lineup" => "Lineup", "programm" => "Programm", "newsletter" => "Newsletter", "infos" => "Infos"];//, "kontakt" => "Kontakt", "impressum" => "Impressum"];
  // $naviRight = ["newsletter" => "Newsletter", "facebook" => "Facebook", "soundcloud" => "Soundcloud"];#"programm" => "Programm","tickets" => "Tickets", "contact" => "Kontakt"];
?>

<div class="left ml pl- palm-pl0 palm-m0">
  <?foreach ($naviLeft as $key => $value) {?>
    <a class='desk-mh- lap-mh- navigation__item gamma <?=$key == "about" ? "active" : ""?> <?=$key == "newsletter" ? "palm-hide" : ""?>' data-target='<?=$key?>' href='#<?=$key?>'><?=$value?></a>
  <?}?>
  <a class='desk-mh- lap-mh- gamma palm-hide' href='mailto:info@animalfarm-festival.de'>Kontakt</a>
</div>
<div class="right mr pr -mt palm-hide">
    <a class='fb-logo mt-' data-target='<?=$key?>' target='_blank' href='https://www.facebook.com/Animal-Farm-Festival-638619299659271/'></a>
    <a class='sc-logo mt-' data-target='<?=$key?>' target='_blank' href='https://soundcloud.com/animalfarmfestival'></a>
</div>
