<div class="wrapper">
  <div class="outer-content center">
    <a class="no-deco pt-" href="https://www.eventbrite.de/e/animal-farm-festival-2017-tickets-32212955818" target="_blank">BUY TICKETS</a>
  </div>
  <div class="content">
    <section id="about-section" class="clear">
      <div class="navigation p+ mb++ palm-p0 palm-m0">
        <?include_once( dirname( __FILE__ ) . '/navigation.phtml' );?>
      </div>

      <?include_once( dirname( __FILE__ ) . '/pages/about.phtml' );?>
      <div class="clear">&nbsp;</div>
    </section>
    <section id="lineup-section" class="clear pt+">
      <?include( dirname( __FILE__ ) . '/pages/lineup_ltr.phtml' );?>
    </section>
    <section id="ads-section" class="clear pv++">
      <?include_once( dirname( __FILE__ ) . '/pages/ads.phtml' );?>
    </section>
    <section id="lineup-section" class="clear pt+">
      <?include( dirname( __FILE__ ) . '/pages/lineup_rtl.phtml' );?>
    </section>
    <section id="infos-section" class="clear pt+ relative">
      <?include_once( dirname( __FILE__ ) . '/pages/infos.phtml' );?>
    </section>
  </div>
</div>
