<div>
  <div class="content">
    <section id="about" class="section clear">
      <div class="navigation pt palm-p0 palm-m0 1/1 stuckMenu isStuck" style="position: fixed; top: 0px;">
        <?include_once( dirname( __FILE__ ) . '/navigation.phtml' );?>
      </div>
      <?include_once( dirname( __FILE__ ) . '/pages/about.phtml' );?>
    </section>
    <section id="news" class="section clear pt+ pb++ center">
      <?include( dirname( __FILE__ ) . '/pages/news.phtml' );?>
    </section>
    <section id="ads" class="section clear pv++">
      <?include_once( dirname( __FILE__ ) . '/pages/ads.phtml' );?>
    </section>
    <section id="lineup" class="section clear pv+">
      <?include( dirname( __FILE__ ) . '/pages/lineup_ltr.phtml' );?>
    </section>
    <section id="programm" class="section clear pv+">
      <?include_once( dirname( __FILE__ ) . '/pages/programm.phtml' );?>
    </section>
    <section id="infos" class="section clear pv+">
      <?include_once( dirname( __FILE__ ) . '/pages/infos.phtml' );?>
    </section>
    <section id="getinthemood" class="section clear pt+ relative">
      <?include_once( dirname( __FILE__ ) . '/pages/getinthemood.phtml' );?>
    </section>
  </div>
</div>
